### ISSUE TITLE
CyberPunk theme for Jetbrains Rider 

### ISSUE THREAD

**Issue by Nadoc18** [T0uchM3/Cyberpunk-Theme#18]
Hi T0uchM3

Your theme is so awesome!!!

I've been using it for months on VS 2022

but I would like to switch to Jetbrains Rider
Think you can create it for Rider?!!

**Comment by h4zm1** [comment]
Hi @Nadoc18, glad to hear you liked it
You see, this theme came from a long period of me using vs
So it was easy to keep it updated and make changes since I was on vs daily
But I can't say the same about Rider...
That being said, am currently doing a project on android studio and I got something similar on it (not public)
I know both ide are from Jetbrains, so maybe they can share the same theme files or something like that?
Well now  I know there's some interest in this ; ) but I can't promise anything right now.
