### ISSUE TITLE
VS2017 support

### ISSUE THREAD

**Issue by scarlettliuu** [T0uchM3/Cyberpunk-Theme#19]
I'm using vs2017, I download your theme and it says it can't be installed on this version. I really love this theme, could you plz support vs2017? Or should I do something to make it install successfully?

**Comment by h4zm1** [comment]
Yeah, this theme only supports vs2019 and 2022, I think I can add support for vs2017 ? but the problem is I need to test it and see how it looks there and change stuff accordingly which I can't since I don't have vs2017 installed.
I actually don't have any vs installed on my current machine right now which explains the lack of updates too.
But it's something I will consider in the future.

**Comment by scarlettliuu** [comment]
> 

Thank you so much!! I'm looking forward to it.

**Comment by djwilson7** [comment]
Hey, on the new preview of 17.9 2022, there seems to be some conflict with the outer edges showing as white instead of the dark blue background, Pic included shows preview 17.9 up top, and 17.8 below. 
![Screenshot 2023-11-21 115227](https://github.com/T0uchM3/Cyberpunk-Theme/assets/145996575/bfb9e5f4-b9a8-4734-aeda-3f77edbaf97a)
